### ISSUE TITLE
./test.sh error which said "cat: time.out: No such file or directory"

### ISSUE THREAD

**Issue by MrMorning** [johnathan79717/codeforces-parser#10]
```
which: no time in (/home/gengchen/.autojump/bin:/home/gengchen/.autojump/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
./test.sh: line 26: -o: command not found
cat: time.out: no such file or directory
Sample test #1: Runtime Error
....
```
I run `which time`, it turned out:
time: shell reserved word

when i deleted the content related to "time", it worked.

OS: Manjaro 17.0.5 Gellivara
Kernel: x86_64 Linux 4.9.50-1-MANJARO
Shell: zsh 5.4.2

**Comment by jakobkogler** [comment]
Your distribution probably doesn't have `time` installed yet. Try installing it with:

    sudo pacman -Syy
    sudo pacman -S time

This should fix the problem. 

And the second observation:
If you run `which time` in zsh, you get a different error message than in the script `./test.sh`. The reason is, that `time` is a reserved word in zsh. So you cannot use `time` in any command. But the script is run by `bash`, and here it is no problem. `time` is no reserved word in `bash`. If you start the terminal with `bash`, you should get the same error message as above. 

    bash
    which time

**Comment by MrMorning** [comment]
Solved. I thought the `time` used here was the command i used to run......
isn't there two `time` command?
